config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :cars
  
  devise_for :users
  root 'home#index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
 

  

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/car_observer.rb
#saved in the file app/models/car_observer.rb
require 'my_logger'

class CarObserver < ActiveRecord::Observer
    
    def after_update(record)
        # use the MyLogger instance method to retrieve the single instance/object of the class
        @logger = MyLogger.instance
        # use the logger to log/record a message about the updated car
        @logger.logInformation("CarObserver Demo:")
        @logger.logInformation("The car of #{record.firstname} #{record.lastname}
        has been updated. cost #{record.cost}")
        
    end
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profiles       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    "/signedinuserprofile"
  end

end

app/controllers/cars_controller.rb
require 'my_logger'
class CarsController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :ensure_admin, :only => [:edit, :destroy]
  
  require 'car_decorator'
  
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new()
    @car.firstname = params[:car][:firstname]
    @car.lastname = params[:car][:lastname]
    @car.color = params[:car][:color]
    #@car.cost = params[:car][:cost]
    @car.manufacturer = params[:car][:manufacturer]
    # create an instance/object of a BasicCar
    myCar = BasicCar.new(15000, @car.manufacturer, @car.color)
    
    # add the extra features to the new car
    if params[:car][:windows].to_s.length > 0 then
     myCar = ElectricWindowsDecorator.new(myCar)
    end
    if params[:car][:mirror].to_s.length > 0 then
      myCar = MirrorDecorator.new(myCar)
    end
    if params[:car][:psensor].to_s.length > 0 then
      myCar = ParkingSensorDecorator.new(myCar)
    end
    ## populate the cost and the description details
    @car.cost = myCar.cost
    @car.description = myCar.details
    
    # retrieve the instance/object of the MyLogger class
    logger = MyLogger.instance
    logger.logInformation("A new car requested: " + @car.description)
    
    respond_to do |format|
    if @car.save
      format.html { redirect_to @car, notice: 'Car was successfully created.'}
      format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
    end
    end
  end

  #my addition - show car update info
  logger = MyLogger.instance
  logger.logInformation("Car details:")

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @car.firstname = params[:car][:firstname]
    @car.lastname = params[:car][:lastname]
    @car.color = params[:car][:color]
    @car.manufacturer = params[:car][:manufacturer]
    # create an instance/object of a BasicCar
    myCar = BasicCar.new(15000, @car.manufacturer, @car.color)
    # add the extra features to the new car if they were selected
    if params[:car][:windows].to_s.length > 0 then
      myCar = ElectricWindowsDecorator.new(myCar)
    end
    if params[:car][:mirror].to_s.length > 0 then
      myCar = MirrorDecorator.new(myCar)
    end
    if params[:car][:psensor].to_s.length > 0 then
      myCar = ParkingSensorDecorator.new(myCar)
    end
    
     ## update the cost and the description details 
    @car.cost = myCar.cost 
    @car.description = myCar.details
    
    # build a hash map with the updated information of the car
    updated_information = {
    "firstname" => @car.firstname,
    "lastname" => @car.lastname,
    "manufacturer" => @car.manufacturer,
    "cost" => @car.cost,
    "description" => @car.description,
    "color" => @car.color
    }
    
    #my addition - show car update info
    logger = MyLogger.instance
    logger.logInformation("A car has been updated: " + @car.description)
    
    respond_to do |format|
      # call the method update of the ActiveRecord instance to update the car with the new information
      if @car.update(updated_information)
      format.html { redirect_to @car, notice: 'Car was successfully updated.' }
      format.json { render :show, status: :ok, location: @car }
      else
      format.html { render :edit }
      format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:firstname, :lastname, :manufacturer, :cost, :description, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
# see the sessions controller

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    #after_sign_in_path_for is called by devise
    #we are over-riding the devise method
    def after_sign_in_path_for(user) 
        "/signedinuserprofile" 
    #here we provide
    #the path for the user's profile
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
  Electric windows:
  <%= check_box_tag 'car[windows]', 'windows' %>
  </div>
  <div class="field">
  Anti glare rear view mirror:
  <%= check_box_tag 'car[mirror]', 'mirror' %>
  </div>
  <div class="field">
  Parking sensor:
  <%= check_box_tag 'car[psensor]', 'psensor' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>
 
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Manufacturer</th>
      <th>Cost</th>
      <th>Description</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.firstname %></td>
        <td><%= car.lastname %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.cost %></td>
        <td><%= car.description %></td>
        <td><%= car.color %></td>
        <td><%= link_to 'Show', car %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- another way to restrict access to only signed users -->


<%# if user_signed_in? %> 
  <%= link_to 'New Car', new_car_path %>
<%# end %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @car.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @car.lastname %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @car.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DecApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h2>Car Decorator App</h2>
    
  
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <% if user_signed_in? %>
      <div>
        Signed in as... <%= current_user.email %> 
        (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete%>)
        <p><%= link_to 'Profiles', profiles_path %> &nbsp; <%= link_to 'Cars', cars_path %></p>

      </div>
          <% else %>
              <%= link_to 'Register', new_user_registration_path %> or
              <%= link_to 'Sign in', new_user_session_path %>
          <% end %>

           
      <%= yield %>
  
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile h1</h1>
<h2>making changes h2</h2>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <!-- <th>Email</th>-->
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
          <%# profile.email %>
        <td><%= profile.user.try(:id) %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>